language: objective-c
script: cd XWalkView; pod install; xcodebuild -workspace XWalkView.xcworkspace -scheme XWalkViewTests -configuration Debug -destination 'platform=iOS simulator,name=iPhone 6' test
